=== cmanlh/DDLGenerator/src/main/resources/schema/ddlGenerator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:ddl="http://www.lifeonwalden.com/ddlGenerator" xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.lifeonwalden.com/ddlGenerator"
        elementFormDefault="qualified">
    <element name="generator">
        <complexType>
            <sequence>
                <element ref="ddl:config"/>
                <element name="constPool" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="enumConst" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="options" minOccurs="0">
                                            <complexType>
                                                <sequence>
                                                    <element ref="ddl:valueEnum" maxOccurs="unbounded"/>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="name" type="string" use="required"/>
                                    <attribute name="note" type="string"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element ref="ddl:database"/>
            </sequence>
        </complexType>
    </element>
    <element name="database">
        <complexType>
            <sequence>
                <element name="dbFields" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element ref="ddl:column" maxOccurs="unbounded"/>
                        </sequence>
                    </complexType>
                </element>
                <element name="tables">
                    <complexType>
                        <sequence>
                            <element name="table" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="columns">
                                            <complexType>
                                                <sequence>
                                                    <element ref="ddl:column" maxOccurs="unbounded"/>
                                                </sequence>
                                            </complexType>
                                        </element>
                                        <element name="extProps" minOccurs="0">
                                            <complexType>
                                                <sequence>
                                                    <element ref="ddl:column" maxOccurs="unbounded"/>
                                                </sequence>
                                            </complexType>
                                        </element>
                                        <element name="constraints" minOccurs="0">
                                            <complexType>
                                                <sequence>
                                                    <element name="constraint" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="columns">
                                                                    <complexType>
                                                                        <sequence>
                                                                            <element ref="ddl:indexColumn"
                                                                                     maxOccurs="unbounded"/>
                                                                        </sequence>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="name" type="string"/>
                                                            <attribute name="type" type="string"/>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                        <element name="indexs" minOccurs="0">
                                            <complexType>
                                                <sequence>
                                                    <element name="index" maxOccurs="unbounded">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="columns">
                                                                    <complexType>
                                                                        <sequence>
                                                                            <element ref="ddl:indexColumn"
                                                                                     maxOccurs="unbounded"/>
                                                                        </sequence>
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="name" type="string"/>
                                                            <attribute name="type" type="string"/>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                        <element name="options" minOccurs="0">
                                            <complexType>
                                                <sequence>
                                                    <element ref="ddl:option" maxOccurs="unbounded"/>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="name" type="string" use="required"/>
                                    <attribute name="note" type="string"/>
                                    <attribute name="addDBFields" type="boolean" default="true"/>
                                    <attribute name="alias" type="string"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
            <attribute name="name" type="string" use="required"/>
            <attribute name="schema" type="string"/>
            <attribute name="note" type="string"/>
            <attribute name="generator" type="string"/>
        </complexType>
    </element>

    <element name="indexColumn">
        <complexType>
            <attribute name="name" type="string" use="required"/>
            <attribute name="order" use="required">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="DESC"/>
                        <enumeration value="ASC"/>
                    </restriction>
                </simpleType>
            </attribute>
        </complexType>
    </element>

    <element name="column">
        <complexType>
            <sequence>
                <element name="options" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element ref="ddl:valueEnum" maxOccurs="unbounded"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
            <attributeGroup ref="ddl:columnAG"/>
        </complexType>
    </element>

    <element name="valueEnum">
        <complexType>
            <attribute name="value" type="string"/>
            <attribute name="name" type="string"/>
            <attribute name="alias" type="string"/>
            <attribute name="desc" type="string"/>
        </complexType>
    </element>

    <attributeGroup name="columnAG">
        <attribute name="name" type="string" use="required"/>
        <attribute name="javaType" type="string"/>
        <attribute name="typeHandler" type="string"/>
        <attribute name="length" type="string"/>
        <attribute name="required" type="boolean" default="false"/>
        <attribute name="defaultVal" type="string"/>
        <attribute name="extra" type="string"/>
        <attribute name="note" type="string"/>
        <attribute name="optionRef" type="string"/>
        <attribute name="type" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="nchar"/>
                    <enumeration value="nvarchar"/>
                    <enumeration value="bit"/>
                    <enumeration value="tinyint"/>
                    <enumeration value="nchar"/>
                    <enumeration value="bigint"/>
                    <enumeration value="longvarbinary"/>
                    <enumeration value="varbinary"/>
                    <enumeration value="longvarchar"/>
                    <enumeration value="null"/>
                    <enumeration value="char"/>
                    <enumeration value="numeric"/>
                    <enumeration value="decimal"/>
                    <enumeration value="integer"/>
                    <enumeration value="smallint"/>
                    <enumeration value="float"/>
                    <enumeration value="real"/>
                    <enumeration value="double"/>
                    <enumeration value="varchar"/>
                    <enumeration value="boolean"/>
                    <enumeration value="datalink"/>
                    <enumeration value="date"/>
                    <enumeration value="time"/>
                    <enumeration value="timestamp"/>
                    <enumeration value="datetime"/>
                    <enumeration value="int"/>
                    <enumeration value="other"/>
                    <enumeration value="java_object"/>
                    <enumeration value="distinct"/>
                    <enumeration value="struct"/>
                    <enumeration value="array"/>
                    <enumeration value="blob"/>
                    <enumeration value="clob"/>
                    <enumeration value="ref"/>
                    <enumeration value="nclob"/>
                </restriction>
            </simpleType>
        </attribute>
    </attributeGroup>
    <element name="config">
        <complexType>
            <sequence>
                <element name="constInfo" minOccurs="0">
                    <complexType>
                        <attribute ref="ddl:packageName" use="required"/>
                        <attribute ref="ddl:folderName" use="required"/>
                        <attribute ref="ddl:namePattern"/>
                    </complexType>
                </element>
                <element name="daoInfo" minOccurs="0">
                    <complexType>
                        <attribute ref="ddl:packageName" use="required"/>
                        <attribute ref="ddl:folderName" use="required"/>
                        <attribute ref="ddl:namePattern"/>
                    </complexType>
                </element>
                <element name="beanInfo" minOccurs="0">
                    <complexType>
                        <attribute ref="ddl:packageName" use="required"/>
                        <attribute ref="ddl:folderName" use="required"/>
                        <attribute name="resultNamePattern" type="string"/>
                        <attribute name="valueObjectPattern" type="string"/>
                        <attribute name="paramNamePattern" type="string"/>
                        <attribute name="generator" type="string">
                            <annotation>
                                <documentation>
                                    generator class name, such as
                                    com.lifeonwalden.codeGenerator.javaClass.impl.BeanGeneratorImpl. It has to extend
                                    com.lifeonwalden.codeGenerator.javaClass.impl.BeanGeneratorImpl
                                </documentation>
                            </annotation>
                        </attribute>
                    </complexType>
                </element>
                <element name="mybatisInfo" minOccurs="0">
                    <complexType>
                        <attribute name="namespace" type="string" use="required">
                            <annotation>
                                <documentation>namespace for mybatis mapping file</documentation>
                            </annotation>
                        </attribute>
                        <attribute name="folderName" type="string" use="required">
                            <annotation>
                                <documentation>output locations for mybatis mapping file</documentation>
                            </annotation>
                        </attribute>
                    </complexType>
                </element>
                <element name="extentions" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="extentionGenerator" maxOccurs="unbounded" minOccurs="0">
                                <complexType>
                                    <sequence>
                                        <element name="options" minOccurs="0">
                                            <complexType>
                                                <sequence>
                                                    <element ref="ddl:option" maxOccurs="unbounded"/>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="generator" type="string"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
            <attribute name="outputLocation" type="string">
                <annotation>
                    <documentation>file locations of output source</documentation>
                </annotation>
            </attribute>
            <attribute name="encoding" type="string" default="UTF-8">
                <annotation>
                    <documentation>output file encoding</documentation>
                </annotation>
            </attribute>
        </complexType>
    </element>
    <element name="option">
        <complexType>
            <attribute name="option" type="string" use="required"/>
            <attribute name="value" type="string" use="required"/>
        </complexType>
    </element>
    <attribute name="packageName" type="string">
        <annotation>
            <documentation>package name of java class, such as com.test</documentation>
        </annotation>
    </attribute>
    <attribute name="folderName" type="string">
        <annotation>
            <documentation>output location for generate source code, such as src or java/dao</documentation>
        </annotation>
    </attribute>
    <attribute name="namePattern" type="string">
        <annotation>
            <documentation>name pattern of output class, such as ?Mapper, the question mark will be replaced by class
                name
            </documentation>
        </annotation>
    </attribute>
</schema>

=== cmanlh/DDLGenerator/src/main/resources/demo-template.xml
<?xml version="1.0" encoding="UTF-8"?>
<generator xmlns="http://www.lifeonwalden.com/ddlGenerator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.lifeonwalden.com/ddlGenerator schema/ddlGenerator.xsd">
	<config encoding="UTF-8">
		<constInfo packageName="com.orientsec.demo.consts" folderName="java" />
		<daoInfo packageName="com.orientsec.demo.dao" folderName="java" namePattern="?Mapper" />
		<beanInfo packageName="com.orientsec.demo.bean" folderName="java" generator="com.lifeonwalden.codeGenerator.javaClass.impl.HashBeanGeneratorImpl"
				  paramNamePattern="?Param" />
		<mybatisInfo namespace="com.orientsec.demo.dao" folderName="resources" />
	</config>
	<constPool>
		<enumConst name="Option" note="OptionEnum">
			<options>
				<valueEnum name="OPTION_001" value="1" alias="001" desc="description001" />
				<valueEnum name="OPTION_002" value="2" alias="002" desc="description002" />
			</options>
		</enumConst>
	</constPool>
	<database name="TestDB" schema="prd" note="test database" generator="com.lifeonwalden.codeGenerator.dll.impl.MSSQLTableGeneratorImpl">
		<dbFields>
			<column name="createTime" type="timestamp" required="true" defaultVal="CURRENT_TIMESTAMP" note="创建时间" />
			<column name="createUser" type="varchar" note="创建者" length="32" />
			<column name="updateTime" type="timestamp" required="true" defaultVal="CURRENT_TIMESTAMP" extra="ON UPDATE CURRENT_TIMESTAMP" note="更新时间" />
			<column name="updateUser" type="varchar" note="更新者" length="32" />
			<column name="logicalDel" type="int" note="逻辑删除" defaultVal="0" />
		</dbFields>
		<tables>
			<table name="TestTable" note="test table">
				<columns>
					<column name="testColumn001" type="varchar" length="20" required="true" defaultVal="hello world" note="note001" optionRef="OptionEnum" />
					<column name="testColumn002" type="int" required="false" defaultVal="hello world" note="note001">
						<options>
							<valueEnum name="OPTION_001" value="1" alias="001" desc="description" />
							<valueEnum name="OPTION_002" value="2" alias="002" desc="description002" />
						</options>
					</column>
				</columns>
				<extProps>
					<column name="name" type="varchar"></column>
				</extProps>
				<constraints>
					<constraint type="PRIMARY KEY" name="PK">
						<columns>
							<indexColumn name="testColumn001" order="DESC" />
						</columns>
					</constraint>
				</constraints>
				<indexs>
					<index name="TestTable_Index" type="UNIQUE">
						<columns>
							<indexColumn name="testColumn002" order="DESC" />
						</columns>
					</index>
				</indexs>
				<options>
					<option option="ENGINE" value="InnoDB" />
				</options>
			</table>

			<table name="TestTable02" note="test table" addDBFields="false">
				<columns>
					<column name="testColumn001" type="varchar" length="20" required="true" defaultVal="hello world" note="note001" optionRef="OptionEnum" />
					<column name="testColumn002" type="int" required="false" defaultVal="hello world" note="note001" />
				</columns>
			</table>
		</tables>
	</database>
</generator>
