=== cmanlh/DDLGenerator/resources/db2xml/dbSourceDDLGenerator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.lifeonwalden.com/dbSourceDDLGenerator"
        xmlns:ddl="http://www.lifeonwalden.com/dbSourceDDLGenerator"
        elementFormDefault="qualified">
    <element name="dbGenerator">
        <complexType>
            <sequence>
                <element ref="ddl:config"/>
                <element ref="ddl:db"/>
            </sequence>
        </complexType>
    </element>
    <element name="db">
        <complexType>
            <sequence>
                <element name="tables">
                    <complexType>
                        <sequence>
                            <element name="dbTable" maxOccurs="unbounded">
                                <complexType>
                                    <sequence>
                                        <element name="extProps">
                                            <complexType>
                                                <sequence>
                                                    <element ref="ddl:column" maxOccurs="unbounded"/>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="name" type="string" use="required"/>
                                    <attribute name="note" type="string"/>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
            <attribute name="name" type="string" use="required"/>
            <attribute name="driverClass" type="string" use="required"/>
            <attribute name="connectionURL" type="string" use="required"/>
            <attribute name="userId" type="string" use="required"/>
            <attribute name="password" type="string" use="required"/>
            <attribute name="schema" type="string"/>
            <attribute name="withSchema" type="boolean"/>
        </complexType>
    </element>

    <element name="column">
        <complexType>
            <sequence>
                <element name="options" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element ref="ddl:valueEnum" maxOccurs="unbounded"/>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
            <attributeGroup ref="ddl:columnAG"/>
        </complexType>
    </element>

    <element name="valueEnum">
        <complexType>
            <attribute name="value" type="string"/>
            <attribute name="name" type="string"/>
            <attribute name="alias" type="string"/>
            <attribute name="desc" type="string"/>
        </complexType>
    </element>

    <attributeGroup name="columnAG">
        <attribute name="name" type="string" use="required"/>
        <attribute name="javaType" type="string"/>
        <attribute name="typeHandler" type="string"/>
        <attribute name="length" type="string"/>
        <attribute name="required" type="boolean" default="false"/>
        <attribute name="defaultVal" type="string"/>
        <attribute name="note" type="string"/>
        <attribute name="optionRef" type="string"/>
        <attribute name="enableIn" type="boolean"/>
        <attribute name="enableLike" type="boolean"/>
        <attribute name="enableNotIn" type="boolean"/>
        <attribute name="enableNotLike" type="boolean"/>
        <attribute name="type" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="nchar"/>
                    <enumeration value="nvarchar"/>
                    <enumeration value="bit"/>
                    <enumeration value="tinyint"/>
                    <enumeration value="nchar"/>
                    <enumeration value="bigint"/>
                    <enumeration value="longvarbinary"/>
                    <enumeration value="varbinary"/>
                    <enumeration value="longvarchar"/>
                    <enumeration value="null"/>
                    <enumeration value="char"/>
                    <enumeration value="numeric"/>
                    <enumeration value="decimal"/>
                    <enumeration value="integer"/>
                    <enumeration value="smallint"/>
                    <enumeration value="float"/>
                    <enumeration value="real"/>
                    <enumeration value="double"/>
                    <enumeration value="varchar"/>
                    <enumeration value="boolean"/>
                    <enumeration value="datalink"/>
                    <enumeration value="date"/>
                    <enumeration value="time"/>
                    <enumeration value="timestamp"/>
                    <enumeration value="datetime"/>
                    <enumeration value="int"/>
                    <enumeration value="other"/>
                    <enumeration value="java_object"/>
                    <enumeration value="distinct"/>
                    <enumeration value="struct"/>
                    <enumeration value="array"/>
                    <enumeration value="blob"/>
                    <enumeration value="clob"/>
                    <enumeration value="ref"/>
                    <enumeration value="nclob"/>
                </restriction>
            </simpleType>
        </attribute>
    </attributeGroup>
    <element name="config">
        <complexType>
            <sequence>
                <element name="daoInfo" minOccurs="0">
                    <complexType>
                        <attribute ref="ddl:packageName" use="required"/>
                        <attribute ref="ddl:folderName" use="required"/>
                        <attribute ref="ddl:namePattern"/>
                    </complexType>
                </element>
                <element name="beanInfo" minOccurs="0">
                    <complexType>
                        <attribute ref="ddl:packageName" use="required"/>
                        <attribute ref="ddl:folderName" use="required"/>
                        <attribute name="resultNamePattern" type="string"/>
                        <attribute name="valueObjectPattern" type="string"/>
                        <attribute name="paramNamePattern" type="string"/>
                        <attribute name="generator" type="string">
                            <annotation>
                                <documentation>
                                    generator class name, such as
                                    com.lifeonwalden.codeGenerator.javaClass.impl.BeanGeneratorImpl. It has to extend
                                    com.lifeonwalden.codeGenerator.javaClass.impl.BeanGeneratorImpl
                                </documentation>
                            </annotation>
                        </attribute>
                    </complexType>
                </element>
                <element name="mybatisInfo" minOccurs="0">
                    <complexType>
                        <attribute name="namespace" type="string" use="required">
                            <annotation>
                                <documentation>namespace for mybatis mapping file</documentation>
                            </annotation>
                        </attribute>
                        <attribute name="folderName" type="string" use="required">
                            <annotation>
                                <documentation>output locations for mybatis mapping file</documentation>
                            </annotation>
                        </attribute>
                    </complexType>
                </element>
                <element name="extentions" minOccurs="0">
                    <complexType>
                        <sequence>
                            <element name="extentionGenerator" maxOccurs="unbounded" minOccurs="0">
                                <complexType>
                                    <sequence>
                                        <element name="options" minOccurs="0">
                                            <complexType>
                                                <sequence>
                                                    <element ref="ddl:option" maxOccurs="unbounded"/>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
            <attribute name="outputLocation" type="string">
                <annotation>
                    <documentation>file locations of output source</documentation>
                </annotation>
            </attribute>
            <attribute name="encoding" type="string" default="UTF-8">
                <annotation>
                    <documentation>output file encoding</documentation>
                </annotation>
            </attribute>
        </complexType>
    </element>
    <element name="option">
        <complexType>
            <attribute name="option" type="string" use="required"/>
            <attribute name="value" type="string" use="required"/>
        </complexType>
    </element>
    <attribute name="packageName" type="string">
        <annotation>
            <documentation>package name of java class, such as com.test</documentation>
        </annotation>
    </attribute>
    <attribute name="folderName" type="string">
        <annotation>
            <documentation>output location for generate source code, such as src or java/dao</documentation>
        </annotation>
    </attribute>
    <attribute name="namePattern" type="string">
        <annotation>
            <documentation>name pattern of output class, such as ?Mapper, the question mark will be replaced by class
                name
            </documentation>
        </annotation>
    </attribute>
</schema>

=== cmanlh/DDLGenerator/resources/db2xml/dbSourceTemplate.xml
<?xml version="1.0" encoding="GB18030"?>
<dbGenerator xmlns="http://www.lifeonwalden.com/dbSourceDDLGenerator" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.lifeonwalden.com/dbSourceDDLGenerator dbSourceDDLGenerator.xsd">
	<config encoding="GB18030">
		<daoInfo packageName="com.test.dao" folderName="dao" namePattern="?Mapper" />
		<beanInfo packageName="com.test.bean" folderName="bean" generator="com.lifeonwalden.codeGenerator.javaClass.impl.HashBeanGeneratorImpl"
			paramNamePattern="?Param" />
		<mybatisInfo namespace="com.test.dao" folderName="xml" />
	</config>
	<db driverClass="org.hsqldb.jdbcDriver" password="" name="testdb" userId="SA" connectionURL="jdbc:hsqldb:mem:testdb;shutdown=false">
		<tables>
			<dbTable name="User">
				<extProps>
					<column name="tel" type="varchar" length="32"></column>
				</extProps>
			</dbTable>
			<dbTable name="Book" />
		</tables>
	</db>
</dbGenerator>
